version: "3"
services:
  # app:
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #   network_mode: "host"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: ${DB_USER}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

