version: "3"
services:
  app:
    env_file:
      - .env
    build:
      context: .
    network_mode: "host"

  db:
    restart: always
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gvampre1991@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - 80:80
    depends_on:
      - db


